# Generated by Django 4.2.21 on 2025-12-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='author',
            name='works',
        ),
    ]
