# Generated by Django 5.2.9 on 2025-12-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_author_image_url_remove_author_summary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionTag',
        ),
    ]
