# Generated by Django 5.2.9 on 2025-12-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_emotiontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.review'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
