# Generated by Django 5.2.9 on 2025-12-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_birthdate_user_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
