# Generated by Django 5.2.9 on 2025-12-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', '학생'), ('highschool', '고등학생'), ('college', '대학생'), ('office', '회사원'), ('unemployed', '백수'), ('homemaker', '주부'), ('jobseeker', '취준생')], max_length=20),
        ),
    ]
